name: Releases

on: 
  push:
    tags:
    - '*'
permissions: write-all

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: | 
        git submodule update --init --recursive
        echo toto > test.txt
        echo toto > roles/nginx/test.txt
        ls -al roles/nginx
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
